#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BASE_SCRIPT="$ROOT_DIR/scripts/run_ssca_retry_grpo_alfworld_base.sh"

if [[ ! -x "$BASE_SCRIPT" ]]; then
  echo "[FATAL] Missing executable base script: $BASE_SCRIPT" >&2
  exit 1
fi

RUN_TAG="${RUN_TAG:-$(date +%Y%m%d_%H%M%S)}"
SEED="${SEED:-2026}"
BASE_EXPERIMENT="${BASE_EXPERIMENT:-ssca_retry_grpo_qwen25_15b_alfworld_full}"
EXPERIMENT_NAME="${EXPERIMENT_NAME:-${BASE_EXPERIMENT}_seed${SEED}_${RUN_TAG}}"

export RUN_TAG
export SEED
export EXPERIMENT_NAME

# Match the GRPO/GiGPO ALFWorld full recipe unless explicitly overridden.
export N_GPUS_PER_NODE="${N_GPUS_PER_NODE:-4}"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2,3}"
export MODEL_PATH="${MODEL_PATH:-Qwen/Qwen2.5-1.5B-Instruct}"
export ENGINE="${ENGINE:-vllm}"
export TRAIN_DATA_SIZE="${TRAIN_DATA_SIZE:-16}"
export VAL_DATA_SIZE="${VAL_DATA_SIZE:-128}"
export TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-16}"
export GROUP_SIZE="${GROUP_SIZE:-8}"
export MAX_ENV_STEPS="${MAX_ENV_STEPS:-50}"
export TOTAL_EPOCHS="${TOTAL_EPOCHS:-150}"
export TEST_FREQ="${TEST_FREQ:-5}"
export SAVE_FREQ="${SAVE_FREQ:--1}"
export VAL_BEFORE_TRAIN="${VAL_BEFORE_TRAIN:-True}"

# Keep Ray from using every physical CPU, while leaving env workers aligned with GRPO/GiGPO.
export RAY_NUM_CPUS="${RAY_NUM_CPUS:-60}"
export ENV_WORKER_CPUS="${ENV_WORKER_CPUS:-0.1}"

# Full training keeps lightweight rollout generations but disables heavy DataProto/token-array trace dumps.
export RL_TRACE_INTERVAL="${RL_TRACE_INTERVAL:-0}"
export RL_TRACE_SAVE_DATAPROTO="${RL_TRACE_SAVE_DATAPROTO:-False}"
export RL_TRACE_INCLUDE_TOKEN_ARRAYS="${RL_TRACE_INCLUDE_TOKEN_ARRAYS:-False}"
export RL_TRACE_INCLUDE_PROB_ARRAYS="${RL_TRACE_INCLUDE_PROB_ARRAYS:-False}"
export RL_TRACE_INCLUDE_FULL_PROMPT_TOKENS="${RL_TRACE_INCLUDE_FULL_PROMPT_TOKENS:-False}"
export RL_TRACE_INCLUDE_TEXT="${RL_TRACE_INCLUDE_TEXT:-True}"

# SSCA summary prompt settings used by the v3 prompt-loop selection.
export SSCA_SUMMARY_CONTEXT_MODE="${SSCA_SUMMARY_CONTEXT_MODE:-compact_obs_trace}"
export SSCA_SUMMARY_TRACE_MAX_STEPS="${SSCA_SUMMARY_TRACE_MAX_STEPS:-6}"
export SSCA_SUMMARY_STEP_OBS_CHARS="${SSCA_SUMMARY_STEP_OBS_CHARS:-240}"
export SSCA_SUMMARY_STEP_FEEDBACK_CHARS="${SSCA_SUMMARY_STEP_FEEDBACK_CHARS:-240}"
export SSCA_SUMMARY_INVALID_RESPONSE_CHARS="${SSCA_SUMMARY_INVALID_RESPONSE_CHARS:-0}"
export SSCA_SUMMARY_MAX_PROMPT_CHARS="${SSCA_SUMMARY_MAX_PROMPT_CHARS:-1200}"
export SSCA_SUMMARY_MAX_CHARS="${SSCA_SUMMARY_MAX_CHARS:-1200}"
export SSCA_SUMMARY_QUALITY_REWARD_COEF="${SSCA_SUMMARY_QUALITY_REWARD_COEF:-0.2}"
export SSCA_SUMMARY_QUALITY_MAX_WORDS="${SSCA_SUMMARY_QUALITY_MAX_WORDS:-110}"

# VIMPO-style auxiliary value loss: retry value target is reward(traj2)-reward(traj1).
export SSCA_VIMPO_ENABLE="${SSCA_VIMPO_ENABLE:-True}"
export SSCA_VIMPO_REWARD_SCALE="${SSCA_VIMPO_REWARD_SCALE:-10.0}"
export SSCA_VIMPO_MARGIN="${SSCA_VIMPO_MARGIN:-0.1}"
export SSCA_VIMPO_TARGET_CLIP="${SSCA_VIMPO_TARGET_CLIP:-2.0}"
export SSCA_VIMPO_TARGET_DISTRIBUTION="${SSCA_VIMPO_TARGET_DISTRIBUTION:-split_by_retry_rows}"
export SSCA_VIMPO_BETA="${SSCA_VIMPO_BETA:-0.01}"
export SSCA_VIMPO_VALUE_LOSS_COEF="${SSCA_VIMPO_VALUE_LOSS_COEF:-0.05}"
export SSCA_VIMPO_KL_ESTIMATOR="${SSCA_VIMPO_KL_ESTIMATOR:-low_var_kl}"
export SSCA_VIMPO_DETACH_KL="${SSCA_VIMPO_DETACH_KL:-True}"
export SSCA_VIMPO_VALUE_LOSS_TYPE="${SSCA_VIMPO_VALUE_LOSS_TYPE:-huber}"
export SSCA_VIMPO_HUBER_DELTA="${SSCA_VIMPO_HUBER_DELTA:-1.0}"
export SSCA_VALUE_HEAD_ENABLE="${SSCA_VALUE_HEAD_ENABLE:-False}"
export SSCA_VALUE_LOSS_COEF="${SSCA_VALUE_LOSS_COEF:-0.0}"
export SSCA_VALUE_CLIPRANGE="${SSCA_VALUE_CLIPRANGE:-0.5}"
export SSCA_VALUE_DETACH_BACKBONE="${SSCA_VALUE_DETACH_BACKBONE:-True}"

LOG_DIR="${LOG_DIR:-$ROOT_DIR/logs}"
export LOG_DIR
export LOG_FILE="${LOG_FILE:-$LOG_DIR/${EXPERIMENT_NAME}_$(date +%Y%m%d_%H%M%S).log}"
export TRACE_DIR="${TRACE_DIR:-$ROOT_DIR/EXPS/analysis/024_ssca_retry_full/${EXPERIMENT_NAME}}"

mkdir -p "$LOG_DIR"

echo "[INFO] ROOT_DIR=$ROOT_DIR"
echo "[INFO] BASE_SCRIPT=$BASE_SCRIPT"
echo "[INFO] EXPERIMENT_NAME=$EXPERIMENT_NAME"
echo "[INFO] SEED=$SEED"
echo "[INFO] TRAIN_DATA_SIZE=$TRAIN_DATA_SIZE VAL_DATA_SIZE=$VAL_DATA_SIZE TRAIN_BATCH_SIZE=$TRAIN_BATCH_SIZE GROUP_SIZE=$GROUP_SIZE"
echo "[INFO] MAX_ENV_STEPS=$MAX_ENV_STEPS TOTAL_EPOCHS=$TOTAL_EPOCHS TEST_FREQ=$TEST_FREQ SAVE_FREQ=$SAVE_FREQ"
echo "[INFO] RAY_NUM_CPUS=$RAY_NUM_CPUS ENV_WORKER_CPUS=$ENV_WORKER_CPUS"
echo "[INFO] RL_TRACE_INTERVAL=$RL_TRACE_INTERVAL RL_TRACE_SAVE_DATAPROTO=$RL_TRACE_SAVE_DATAPROTO RL_TRACE_INCLUDE_TOKEN_ARRAYS=$RL_TRACE_INCLUDE_TOKEN_ARRAYS"
echo "[INFO] SSCA_SUMMARY_QUALITY_REWARD_COEF=$SSCA_SUMMARY_QUALITY_REWARD_COEF SSCA_SUMMARY_QUALITY_MAX_WORDS=$SSCA_SUMMARY_QUALITY_MAX_WORDS"
echo "[INFO] SSCA_VIMPO_ENABLE=$SSCA_VIMPO_ENABLE SSCA_VIMPO_MARGIN=$SSCA_VIMPO_MARGIN SSCA_VIMPO_BETA=$SSCA_VIMPO_BETA SSCA_VIMPO_VALUE_LOSS_COEF=$SSCA_VIMPO_VALUE_LOSS_COEF"
echo "[INFO] LOG_FILE=$LOG_FILE"
echo "[INFO] TRACE_DIR=$TRACE_DIR"

bash "$BASE_SCRIPT" "$@"
